// IR layer — Zod schemas (single source of truth) + inferred TS types + JSON-Schema export.
// Story IR (semantic, YAML-authored) and Scene IR (concrete, Remotion inputProps, Lottie superset).
// See spec §6 (the two-layer IR), §7 (layer taxonomy), §15 (M1 subset).
//
// Other modules import from here. Schemas end in `Schema`; their inferred types share the base name.

// Animated-property convention (`{a,k}` Lottie superset) + value primitives.
export {
  animated,
  staticProp,
  keyframe,
  EasingRefSchema,
  ColorSchema,
  Vec2Schema,
  AnimatedNumberSchema,
  AnimatedVec2Schema,
  AnimatedColorSchema,
  NumberKeyframeSchema,
} from './animated.js';
export type {
  EasingRef,
  Color,
  Vec2,
  AnimatedNumber,
  AnimatedVec2,
  AnimatedColor,
  NumberKeyframe,
} from './animated.js';

// Story IR.
export {
  StoryIRSchema,
  CastEntrySchema,
  VoiceSchema,
  BeatSchema,
  ShowItemSchema,
  ActionItemSchema,
  PlaceItemSchema,
  CameraIntentSchema,
  DurationSchema,
  StoryTransitionSchema,
  FormatSchema,
  AspectSchema,
  MusicSchema,
} from './story.js';
export type {
  StoryIR,
  CastEntry,
  Voice,
  Beat,
  ShowItem,
  ActionItem,
  PlaceItem,
  CameraIntent,
  Duration,
  StoryTransition,
  Format,
  Aspect,
  Music,
} from './story.js';

// StyleKit IR schema (ADR-008 I2) — pure Zod shape of a selectable house style (no render dep).
export {
  StyleKitSchema,
  CubicBezierSchema,
  StyleEasingDefSchema,
  SpringConfigSchema,
  IdleSchema,
  BreathingSchema,
  BlinkSchema,
  StaggerSchema,
  ParallaxSchema,
  StyleMotionSchema,
  StyleLightSchema,
  StyleShadingSchema,
  FloorSchema,
} from './stylekit.js';
export type {
  StyleKit,
  CubicBezier,
  StyleEasingDef,
  SpringConfig,
  Idle,
  Breathing,
  Blink,
  Stagger,
  Parallax,
  StyleMotion,
  StyleLight,
  StyleShading,
  Floor,
} from './stylekit.js';

// Scene IR.
export {
  SceneIRSchema,
  SceneConfigSchema,
  DefsSchema,
  PaletteSchema,
  EasingsSchema,
  EasingDefSchema,
  AssetDefSchema,
  RigDefSchema,
  RigMountSchema,
  CameraSchema,
  SceneSchema,
  LayerSchema,
  AssetLayerSchema,
  RigLayerSchema,
  GeneratorLayerSchema,
  ShapeLayerSchema,
  TextLayerSchema,
  ClipLayerSchema,
  FootageLayerSchema,
  BlendModeSchema,
  MatteSchema,
  ClipDefSchema,
  ClipParamSchema,
  ClipsSchema,
  TextAnimSchema,
  TransformSchema,
  RigStateSchema,
  RigClipSchema,
  FillSchema,
  GradientFillSchema,
  StrokeSchema,
  ShapePrimitiveSchema,
  MorphChannelSchema,
  EffectSchema,
  PostSchema,
  ShadingSchema,
  LightSchema,
  AttachSchema,
  StaggerGroupSchema,
  TransitionSchema,
  AudioCueSchema,
  CaptionCueSchema,
  TimedWordSchema,
  MouthTrackSchema,
  ProvenanceSchema,
} from './scene.js';
export type {
  SceneIR,
  SceneConfig,
  Defs,
  Palette,
  Easings,
  EasingDef,
  AssetDef,
  RigDef,
  RigMount,
  Camera,
  Scene,
  Layer,
  AssetLayer,
  RigLayer,
  GeneratorLayer,
  ShapeLayer,
  TextLayer,
  ClipLayer,
  FootageLayer,
  BlendMode,
  Matte,
  ClipDef,
  ClipParam,
  Clips,
  TextAnim,
  Transform,
  RigState,
  RigClip,
  Fill,
  GradientFill,
  Stroke,
  ShapePrimitive,
  Effect,
  Post,
  Transition,
  AudioCue,
  CaptionCue,
  TimedWord,
  MouthTrack,
  Provenance,
} from './scene.js';

// Validation helpers + JSON-Schema export.
export {
  validate,
  safeValidate,
  validateStoryIR,
  validateSceneIR,
  validateLayer,
  storyIRJsonSchema,
  sceneIRJsonSchema,
} from './validate.js';
